// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = never
type AppRouteHandlerRoutes = "/api/admin/create-user" | "/api/admin/revoke-access" | "/api/applications/fetch-zoho-deals" | "/api/auth/forgot-password" | "/api/auth/password-changed" | "/api/auth/reset-password" | "/api/auth/verify-zoho" | "/api/chat/admin/conversations" | "/api/chat/messages" | "/api/chat/send" | "/api/chat/widget/messages" | "/api/chat/widget/send" | "/api/corrections" | "/api/deals/[dealId]" | "/api/intake/dependents" | "/api/intake/sync-dependent" | "/api/messages/create" | "/api/messages/fetch" | "/api/messages/upload-attachment" | "/api/profile/fetch-zoho" | "/api/profile/sync-zoho" | "/api/profile/zoho-population-status" | "/api/questionnaires/count" | "/api/resources/shared" | "/api/resources/template" | "/api/review-pdf/application/[matterId]" | "/api/review-pdf/application/[matterId]/draft" | "/api/test/zoho-get" | "/api/test/zoho-update" | "/api/test/zoho-verify-token" | "/api/uploads/matter-documents" | "/api/uploads/matter-documents/comment" | "/api/uploads/zoho" | "/api/webhooks/zoho-contact-update"
type PageRoutes = never
type LayoutRoutes = "/" | "/applications/[slug]/[id]" | "/intake"
type RedirectRoutes = never
type RewriteRoutes = "/applications/186/[appId]/intake/[[...path]]" | "/applications/482/[appId]/intake/[[...path]]" | "/applications/820/[appId]/intake/[[...path]]" | "/applications/866/[appId]/intake/[[...path]]" | "/applications/partner/[appId]/intake/[[...path]]" | "/applications/protection/[appId]/intake/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/admin/create-user": {}
  "/api/admin/revoke-access": {}
  "/api/applications/fetch-zoho-deals": {}
  "/api/auth/forgot-password": {}
  "/api/auth/password-changed": {}
  "/api/auth/reset-password": {}
  "/api/auth/verify-zoho": {}
  "/api/chat/admin/conversations": {}
  "/api/chat/messages": {}
  "/api/chat/send": {}
  "/api/chat/widget/messages": {}
  "/api/chat/widget/send": {}
  "/api/corrections": {}
  "/api/deals/[dealId]": { "dealId": string; }
  "/api/intake/dependents": {}
  "/api/intake/sync-dependent": {}
  "/api/messages/create": {}
  "/api/messages/fetch": {}
  "/api/messages/upload-attachment": {}
  "/api/profile/fetch-zoho": {}
  "/api/profile/sync-zoho": {}
  "/api/profile/zoho-population-status": {}
  "/api/questionnaires/count": {}
  "/api/resources/shared": {}
  "/api/resources/template": {}
  "/api/review-pdf/application/[matterId]": { "matterId": string; }
  "/api/review-pdf/application/[matterId]/draft": { "matterId": string; }
  "/api/test/zoho-get": {}
  "/api/test/zoho-update": {}
  "/api/test/zoho-verify-token": {}
  "/api/uploads/matter-documents": {}
  "/api/uploads/matter-documents/comment": {}
  "/api/uploads/zoho": {}
  "/api/webhooks/zoho-contact-update": {}
  "/applications/[slug]/[id]": { "slug": string; "id": string; }
  "/applications/186/[appId]/intake/[[...path]]": { "appId": string; "path"?: string[]; }
  "/applications/482/[appId]/intake/[[...path]]": { "appId": string; "path"?: string[]; }
  "/applications/820/[appId]/intake/[[...path]]": { "appId": string; "path"?: string[]; }
  "/applications/866/[appId]/intake/[[...path]]": { "appId": string; "path"?: string[]; }
  "/applications/partner/[appId]/intake/[[...path]]": { "appId": string; "path"?: string[]; }
  "/applications/protection/[appId]/intake/[[...path]]": { "appId": string; "path"?: string[]; }
  "/intake": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/applications/[slug]/[id]": never
  "/intake": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
