export const COUNTRY_CODES = [
    { name: "Afghanistan", code: "93", label: "Afghanistan (93)" },
    { name: "Albania", code: "355", label: "Albania (355)" },
    { name: "Algeria", code: "213", label: "Algeria (213)" },
    { name: "American Samoa", code: "1-684", label: "American Samoa (1-684)" },
    { name: "Andorra", code: "376", label: "Andorra (376)" },
    { name: "Angola", code: "244", label: "Angola (244)" },
    { name: "Anguilla", code: "1-264", label: "Anguilla (1-264)" },
    { name: "Antarctica", code: "672", label: "Antarctica (672)" },
    { name: "Antigua and Barbuda", code: "1-268", label: "Antigua and Barbuda (1-268)" },
    { name: "Argentina", code: "54", label: "Argentina (54)" },
    { name: "Armenia", code: "374", label: "Armenia (374)" },
    { name: "Aruba", code: "297", label: "Aruba (297)" },
    { name: "Australia", code: "61", label: "Australia (61)" },
    { name: "Austria", code: "43", label: "Austria (43)" },
    { name: "Azerbaijan", code: "994", label: "Azerbaijan (994)" },
    { name: "Bahamas", code: "1-242", label: "Bahamas (1-242)" },
    { name: "Bahrain", code: "973", label: "Bahrain (973)" },
    { name: "Bangladesh", code: "880", label: "Bangladesh (880)" },
    { name: "Barbados", code: "1-246", label: "Barbados (1-246)" },
    { name: "Belarus", code: "375", label: "Belarus (375)" },
    { name: "Belgium", code: "32", label: "Belgium (32)" },
    { name: "Belize", code: "501", label: "Belize (501)" },
    { name: "Benin", code: "229", label: "Benin (229)" },
    { name: "Bermuda", code: "1-441", label: "Bermuda (1-441)" },
    { name: "Bhutan", code: "975", label: "Bhutan (975)" },
    { name: "Bolivia", code: "591", label: "Bolivia (591)" },
    { name: "Bosnia and Herzegovina", code: "387", label: "Bosnia and Herzegovina (387)" },
    { name: "Botswana", code: "267", label: "Botswana (267)" },
    { name: "Brazil", code: "55", label: "Brazil (55)" },
    { name: "British Indian Ocean Territory", code: "246", label: "British Indian Ocean Territory (246)" },
    { name: "British Virgin Islands", code: "1-284", label: "British Virgin Islands (1-284)" },
    { name: "Brunei", code: "673", label: "Brunei (673)" },
    { name: "Bulgaria", code: "359", label: "Bulgaria (359)" },
    { name: "Burkina Faso", code: "226", label: "Burkina Faso (226)" },
    { name: "Burundi", code: "257", label: "Burundi (257)" },
    { name: "Cambodia", code: "855", label: "Cambodia (855)" },
    { name: "Cameroon", code: "237", label: "Cameroon (237)" },
    { name: "Canada", code: "1", label: "Canada (1)" },
    { name: "Cape Verde", code: "238", label: "Cape Verde (238)" },
    { name: "Cayman Islands", code: "1-345", label: "Cayman Islands (1-345)" },
    { name: "Central African Republic", code: "236", label: "Central African Republic (236)" },
    { name: "Chad", code: "235", label: "Chad (235)" },
    { name: "Chile", code: "56", label: "Chile (56)" },
    { name: "China", code: "86", label: "China (86)" },
    { name: "Christmas Island", code: "61", label: "Christmas Island (61)" },
    { name: "Cocos Islands", code: "61", label: "Cocos Islands (61)" },
    { name: "Colombia", code: "57", label: "Colombia (57)" },
    { name: "Comoros", code: "269", label: "Comoros (269)" },
    { name: "Cook Islands", code: "682", label: "Cook Islands (682)" },
    { name: "Costa Rica", code: "506", label: "Costa Rica (506)" },
    { name: "Croatia", code: "385", label: "Croatia (385)" },
    { name: "Cuba", code: "53", label: "Cuba (53)" },
    { name: "Curacao", code: "599", label: "Curacao (599)" },
    { name: "Cyprus", code: "357", label: "Cyprus (357)" },
    { name: "Czech Republic", code: "420", label: "Czech Republic (420)" },
    { name: "Democratic Republic of the Congo", code: "243", label: "Democratic Republic of the Congo (243)" },
    { name: "Denmark", code: "45", label: "Denmark (45)" },
    { name: "Djibouti", code: "253", label: "Djibouti (253)" },
    { name: "Dominica", code: "1-767", label: "Dominica (1-767)" },
    { name: "Dominican Republic", code: "1-809, 1-829, 1-849", label: "Dominican Republic (1-809, 1-829, 1-849)" },
    { name: "East Timor", code: "670", label: "East Timor (670)" },
    { name: "Ecuador", code: "593", label: "Ecuador (593)" },
    { name: "Egypt", code: "20", label: "Egypt (20)" },
    { name: "El Salvador", code: "503", label: "El Salvador (503)" },
    { name: "Equatorial Guinea", code: "240", label: "Equatorial Guinea (240)" },
    { name: "Eritrea", code: "291", label: "Eritrea (291)" },
    { name: "Estonia", code: "372", label: "Estonia (372)" },
    { name: "Ethiopia", code: "251", label: "Ethiopia (251)" },
    { name: "Falkland Islands", code: "500", label: "Falkland Islands (500)" },
    { name: "Faroe Islands", code: "298", label: "Faroe Islands (298)" },
    { name: "Fiji", code: "679", label: "Fiji (679)" },
    { name: "Finland", code: "358", label: "Finland (358)" },
    { name: "France", code: "33", label: "France (33)" },
    { name: "French Polynesia", code: "689", label: "French Polynesia (689)" },
    { name: "Gabon", code: "241", label: "Gabon (241)" },
    { name: "Gambia", code: "220", label: "Gambia (220)" },
    { name: "Georgia", code: "995", label: "Georgia (995)" },
    { name: "Germany", code: "49", label: "Germany (49)" },
    { name: "Ghana", code: "233", label: "Ghana (233)" },
    { name: "Gibraltar", code: "350", label: "Gibraltar (350)" },
    { name: "Greece", code: "30", label: "Greece (30)" },
    { name: "Greenland", code: "299", label: "Greenland (299)" },
    { name: "Grenada", code: "1-473", label: "Grenada (1-473)" },
    { name: "Guam", code: "1-671", label: "Guam (1-671)" },
    { name: "Guatemala", code: "502", label: "Guatemala (502)" },
    { name: "Guernsey", code: "44-1481", label: "Guernsey (44-1481)" },
    { name: "Guinea", code: "224", label: "Guinea (224)" },
    { name: "Guinea-Bissau", code: "245", label: "Guinea-Bissau (245)" },
    { name: "Guyana", code: "592", label: "Guyana (592)" },
    { name: "Haiti", code: "509", label: "Haiti (509)" },
    { name: "Honduras", code: "504", label: "Honduras (504)" },
    { name: "Hong Kong", code: "852", label: "Hong Kong (852)" },
    { name: "Hungary", code: "36", label: "Hungary (36)" },
    { name: "Iceland", code: "354", label: "Iceland (354)" },
    { name: "India", code: "91", label: "India (91)" },
    { name: "Indonesia", code: "62", label: "Indonesia (62)" },
    { name: "Iran", code: "98", label: "Iran (98)" },
    { name: "Iraq", code: "964", label: "Iraq (964)" },
    { name: "Ireland", code: "353", label: "Ireland (353)" },
    { name: "Isle of Man", code: "44-1624", label: "Isle of Man (44-1624)" },
    { name: "Israel", code: "972", label: "Israel (972)" },
    { name: "Italy", code: "39", label: "Italy (39)" },
    { name: "Ivory Coast", code: "225", label: "Ivory Coast (225)" },
    { name: "Jamaica", code: "1-876", label: "Jamaica (1-876)" },
    { name: "Japan", code: "81", label: "Japan (81)" },
    { name: "Jersey", code: "44-1534", label: "Jersey (44-1534)" },
    { name: "Jordan", code: "962", label: "Jordan (962)" },
    { name: "Kazakhstan", code: "7", label: "Kazakhstan (7)" },
    { name: "Kenya", code: "254", label: "Kenya (254)" },
    { name: "Kiribati", code: "686", label: "Kiribati (686)" },
    { name: "Kosovo", code: "383", label: "Kosovo (383)" },
    { name: "Kuwait", code: "965", label: "Kuwait (965)" },
    { name: "Kyrgyzstan", code: "996", label: "Kyrgyzstan (996)" },
    { name: "Laos", code: "856", label: "Laos (856)" },
    { name: "Latvia", code: "371", label: "Latvia (371)" },
    { name: "Lebanon", code: "961", label: "Lebanon (961)" },
    { name: "Lesotho", code: "266", label: "Lesotho (266)" },
    { name: "Liberia", code: "231", label: "Liberia (231)" },
    { name: "Libya", code: "218", label: "Libya (218)" },
    { name: "Liechtenstein", code: "423", label: "Liechtenstein (423)" },
    { name: "Lithuania", code: "370", label: "Lithuania (370)" },
    { name: "Luxembourg", code: "352", label: "Luxembourg (352)" },
    { name: "Macau", code: "853", label: "Macau (853)" },
    { name: "Macedonia", code: "389", label: "Macedonia (389)" },
    { name: "Madagascar", code: "261", label: "Madagascar (261)" },
    { name: "Malawi", code: "265", label: "Malawi (265)" },
    { name: "Malaysia", code: "60", label: "Malaysia (60)" },
    { name: "Maldives", code: "960", label: "Maldives (960)" },
    { name: "Mali", code: "223", label: "Mali (223)" },
    { name: "Malta", code: "356", label: "Malta (356)" },
    { name: "Marshall Islands", code: "692", label: "Marshall Islands (692)" },
    { name: "Mauritania", code: "222", label: "Mauritania (222)" },
    { name: "Mauritius", code: "230", label: "Mauritius (230)" },
    { name: "Mayotte", code: "262", label: "Mayotte (262)" },
    { name: "Mexico", code: "52", label: "Mexico (52)" },
    { name: "Micronesia", code: "691", label: "Micronesia (691)" },
    { name: "Moldova", code: "373", label: "Moldova (373)" },
    { name: "Monaco", code: "377", label: "Monaco (377)" },
    { name: "Mongolia", code: "976", label: "Mongolia (976)" },
    { name: "Montenegro", code: "382", label: "Montenegro (382)" },
    { name: "Montserrat", code: "1-664", label: "Montserrat (1-664)" },
    { name: "Morocco", code: "212", label: "Morocco (212)" },
    { name: "Mozambique", code: "258", label: "Mozambique (258)" },
    { name: "Myanmar", code: "95", label: "Myanmar (95)" },
    { name: "Namibia", code: "264", label: "Namibia (264)" },
    { name: "Nauru", code: "674", label: "Nauru (674)" },
    { name: "Nepal", code: "977", label: "Nepal (977)" },
    { name: "Netherlands", code: "31", label: "Netherlands (31)" },
    { name: "Netherlands Antilles", code: "599", label: "Netherlands Antilles (599)" },
    { name: "New Caledonia", code: "687", label: "New Caledonia (687)" },
    { name: "New Zealand", code: "64", label: "New Zealand (64)" },
    { name: "Nicaragua", code: "505", label: "Nicaragua (505)" },
    { name: "Niger", code: "227", label: "Niger (227)" },
    { name: "Nigeria", code: "234", label: "Nigeria (234)" },
    { name: "Niue", code: "683", label: "Niue (683)" },
    { name: "North Korea", code: "850", label: "North Korea (850)" },
    { name: "Northern Mariana Islands", code: "1-670", label: "Northern Mariana Islands (1-670)" },
    { name: "Norway", code: "47", label: "Norway (47)" },
    { name: "Oman", code: "968", label: "Oman (968)" },
    { name: "Pakistan", code: "92", label: "Pakistan (92)" },
    { name: "Palau", code: "680", label: "Palau (680)" },
    { name: "Palestine", code: "970", label: "Palestine (970)" },
    { name: "Panama", code: "507", label: "Panama (507)" },
    { name: "Papua New Guinea", code: "675", label: "Papua New Guinea (675)" },
    { name: "Paraguay", code: "595", label: "Paraguay (595)" },
    { name: "Peru", code: "51", label: "Peru (51)" },
    { name: "Philippines", code: "63", label: "Philippines (63)" },
    { name: "Pitcairn", code: "64", label: "Pitcairn (64)" },
    { name: "Poland", code: "48", label: "Poland (48)" },
    { name: "Portugal", code: "351", label: "Portugal (351)" },
    { name: "Puerto Rico", code: "1-787, 1-939", label: "Puerto Rico (1-787, 1-939)" },
    { name: "Qatar", code: "974", label: "Qatar (974)" },
    { name: "Republic of the Congo", code: "242", label: "Republic of the Congo (242)" },
    { name: "Reunion", code: "262", label: "Reunion (262)" },
    { name: "Romania", code: "40", label: "Romania (40)" },
    { name: "Russia", code: "7", label: "Russia (7)" },
    { name: "Rwanda", code: "250", label: "Rwanda (250)" },
    { name: "Saint Barthelemy", code: "590", label: "Saint Barthelemy (590)" },
    { name: "Saint Helena", code: "290", label: "Saint Helena (290)" },
    { name: "Saint Kitts and Nevis", code: "1-869", label: "Saint Kitts and Nevis (1-869)" },
    { name: "Saint Lucia", code: "1-758", label: "Saint Lucia (1-758)" },
    { name: "Saint Martin", code: "590", label: "Saint Martin (590)" },
    { name: "Saint Pierre and Miquelon", code: "508", label: "Saint Pierre and Miquelon (508)" },
    { name: "Saint Vincent and the Grenadines", code: "1-784", label: "Saint Vincent and the Grenadines (1-784)" },
    { name: "Samoa", code: "685", label: "Samoa (685)" },
    { name: "San Marino", code: "378", label: "San Marino (378)" },
    { name: "Sao Tome and Principe", code: "239", label: "Sao Tome and Principe (239)" },
    { name: "Saudi Arabia", code: "966", label: "Saudi Arabia (966)" },
    { name: "Senegal", code: "221", label: "Senegal (221)" },
    { name: "Serbia", code: "381", label: "Serbia (381)" },
    { name: "Seychelles", code: "248", label: "Seychelles (248)" },
    { name: "Sierra Leone", code: "232", label: "Sierra Leone (232)" },
    { name: "Singapore", code: "65", label: "Singapore (65)" },
    { name: "Sint Maarten", code: "1-721", label: "Sint Maarten (1-721)" },
    { name: "Slovakia", code: "421", label: "Slovakia (421)" },
    { name: "Slovenia", code: "386", label: "Slovenia (386)" },
    { name: "Solomon Islands", code: "677", label: "Solomon Islands (677)" },
    { name: "Somalia", code: "252", label: "Somalia (252)" },
    { name: "South Africa", code: "27", label: "South Africa (27)" },
    { name: "South Korea", code: "82", label: "South Korea (82)" },
    { name: "South Sudan", code: "211", label: "South Sudan (211)" },
    { name: "Spain", code: "34", label: "Spain (34)" },
    { name: "Sri Lanka", code: "94", label: "Sri Lanka (94)" },
    { name: "Sudan", code: "249", label: "Sudan (249)" },
    { name: "Suriname", code: "597", label: "Suriname (597)" },
    { name: "Svalbard and Jan Mayen", code: "47", label: "Svalbard and Jan Mayen (47)" },
    { name: "Swaziland", code: "268", label: "Swaziland (268)" },
    { name: "Sweden", code: "46", label: "Sweden (46)" },
    { name: "Switzerland", code: "41", label: "Switzerland (41)" },
    { name: "Syria", code: "963", label: "Syria (963)" },
    { name: "Taiwan", code: "886", label: "Taiwan (886)" },
    { name: "Tajikistan", code: "992", label: "Tajikistan (992)" },
    { name: "Tanzania", code: "255", label: "Tanzania (255)" },
    { name: "Thailand", code: "66", label: "Thailand (66)" },
    { name: "Togo", code: "228", label: "Togo (228)" },
    { name: "Tokelau", code: "690", label: "Tokelau (690)" },
    { name: "Tonga", code: "676", label: "Tonga (676)" },
    { name: "Trinidad and Tobago", code: "1-868", label: "Trinidad and Tobago (1-868)" },
    { name: "Tunisia", code: "216", label: "Tunisia (216)" },
    { name: "Turkey", code: "90", label: "Turkey (90)" },
    { name: "Turkmenistan", code: "993", label: "Turkmenistan (993)" },
    { name: "Turks and Caicos Islands", code: "1-649", label: "Turks and Caicos Islands (1-649)" },
    { name: "Tuvalu", code: "688", label: "Tuvalu (688)" },
    { name: "U.S. Virgin Islands", code: "1-340", label: "U.S. Virgin Islands (1-340)" },
    { name: "Uganda", code: "256", label: "Uganda (256)" },
    { name: "Ukraine", code: "380", label: "Ukraine (380)" },
    { name: "United Arab Emirates", code: "971", label: "United Arab Emirates (971)" },
    { name: "United Kingdom", code: "44", label: "United Kingdom (44)" },
    { name: "United States", code: "1", label: "United States (1)" },
    { name: "Uruguay", code: "598", label: "Uruguay (598)" },
    { name: "Uzbekistan", code: "998", label: "Uzbekistan (998)" },
    { name: "Vanuatu", code: "678", label: "Vanuatu (678)" },
    { name: "Vatican City", code: "379", label: "Vatican City (379)" },
    { name: "Venezuela", code: "58", label: "Venezuela (58)" },
    { name: "Vietnam", code: "84", label: "Vietnam (84)" },
    { name: "Wallis and Futuna", code: "681", label: "Wallis and Futuna (681)" },
    { name: "Western Sahara", code: "212", label: "Western Sahara (212)" },
    { name: "Yemen", code: "967", label: "Yemen (967)" },
    { name: "Zambia", code: "260", label: "Zambia (260)" },
    { name: "Zimbabwe", code: "263", label: "Zimbabwe (263)" },
];
